// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_TimeHour;
extern lv_obj_t * ui_TimeMin;
extern lv_obj_t * ui_TimeSec;
extern lv_obj_t * ui_Air;
extern lv_obj_t * ui_AirValue;
extern lv_obj_t * ui_SliderTemp;
extern lv_obj_t * ui_SliderHum;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_Hum;
extern lv_obj_t * ui_Year;
extern lv_obj_t * ui_Month;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_Week;
extern lv_obj_t * ui_uDay;
extern lv_obj_t * ui_TextDay;
extern lv_obj_t * ui_MinTemp;
extern lv_obj_t * ui_MaxTemp;
extern lv_obj_t * ui_outHum;
extern lv_obj_t * ui_weatherImg;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_cloudy_png);    // assets\cloudy.png
LV_IMG_DECLARE(ui_img_ventilate_png);    // assets\ventilate.png
LV_IMG_DECLARE(ui_img_curtain_png);    // assets\curtain.png
LV_IMG_DECLARE(ui_img_light_png);    // assets\light.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets\battery.png
LV_IMG_DECLARE(ui_img_6g_png);    // assets\6g.png
LV_IMG_DECLARE(ui_img_signal_png);    // assets\signal.png
LV_IMG_DECLARE(ui_img_location_png);    // assets\location.png
LV_IMG_DECLARE(ui_img_air_conditioner_png);    // assets\air_conditioner.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets\temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets\humidity.png
LV_IMG_DECLARE(ui_img_back_png);    // assets\back.png
LV_IMG_DECLARE(ui_img_leave_png);    // assets\leave.png
LV_IMG_DECLARE(ui_img_visitor_png);    // assets\visitor.png
LV_IMG_DECLARE(ui_img_sleep_png);    // assets\sleep.png
LV_IMG_DECLARE(ui_img_air_png);    // assets\air.png
LV_IMG_DECLARE(ui_img_air_conditioner_panel_png);    // assets\air_conditioner_panel.png
LV_IMG_DECLARE(ui_img_icons_00_png);    // assets\icons\00.png
LV_IMG_DECLARE(ui_img_icons_01_png);    // assets\icons\01.png
LV_IMG_DECLARE(ui_img_icons_02_png);    // assets\icons\02.png
LV_IMG_DECLARE(ui_img_icons_03_png);    // assets\icons\03.png
LV_IMG_DECLARE(ui_img_icons_04_png);    // assets\icons\04.png
LV_IMG_DECLARE(ui_img_icons_05_png);    // assets\icons\05.png
LV_IMG_DECLARE(ui_img_icons_06_png);    // assets\icons\06.png
LV_IMG_DECLARE(ui_img_icons_07_png);    // assets\icons\07.png
LV_IMG_DECLARE(ui_img_icons_08_png);    // assets\icons\08.png
LV_IMG_DECLARE(ui_img_icons_09_png);    // assets\icons\09.png
LV_IMG_DECLARE(ui_img_icons_10_png);    // assets\icons\10.png
LV_IMG_DECLARE(ui_img_icons_11_png);    // assets\icons\11.png
LV_IMG_DECLARE(ui_img_icons_12_png);    // assets\icons\12.png
LV_IMG_DECLARE(ui_img_icons_13_png);    // assets\icons\13.png
LV_IMG_DECLARE(ui_img_icons_14_png);    // assets\icons\14.png
LV_IMG_DECLARE(ui_img_icons_15_png);    // assets\icons\15.png
LV_IMG_DECLARE(ui_img_icons_16_png);    // assets\icons\16.png
LV_IMG_DECLARE(ui_img_icons_17_png);    // assets\icons\17.png
LV_IMG_DECLARE(ui_img_icons_18_png);    // assets\icons\18.png
LV_IMG_DECLARE(ui_img_icons_19_png);    // assets\icons\19.png
LV_IMG_DECLARE(ui_img_icons_20_png);    // assets\icons\20.png
LV_IMG_DECLARE(ui_img_icons_21_png);    // assets\icons\21.png
LV_IMG_DECLARE(ui_img_icons_22_png);    // assets\icons\22.png
LV_IMG_DECLARE(ui_img_icons_23_png);    // assets\icons\23.png
LV_IMG_DECLARE(ui_img_icons_24_png);    // assets\icons\24.png
LV_IMG_DECLARE(ui_img_icons_25_png);    // assets\icons\25.png
LV_IMG_DECLARE(ui_img_icons_26_png);    // assets\icons\26.png
LV_IMG_DECLARE(ui_img_icons_27_png);    // assets\icons\27.png
LV_IMG_DECLARE(ui_img_icons_28_png);    // assets\icons\28.png
LV_IMG_DECLARE(ui_img_icons_29_png);    // assets\icons\29.png
LV_IMG_DECLARE(ui_img_icons_30_png);    // assets\icons\30.png
LV_IMG_DECLARE(ui_img_icons_31_png);    // assets\icons\31.png
LV_IMG_DECLARE(ui_img_icons_32_png);    // assets\icons\32.png
LV_IMG_DECLARE(ui_img_icons_33_png);    // assets\icons\33.png
LV_IMG_DECLARE(ui_img_icons_34_png);    // assets\icons\34.png
LV_IMG_DECLARE(ui_img_icons_35_png);    // assets\icons\35.png
LV_IMG_DECLARE(ui_img_icons_36_png);    // assets\icons\36.png
LV_IMG_DECLARE(ui_img_icons_37_png);    // assets\icons\37.png
LV_IMG_DECLARE(ui_img_icons_38_png);    // assets\icons\38.png
LV_IMG_DECLARE(ui_img_icons_99_png);    // assets\icons\99.png

LV_FONT_DECLARE(ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
